dist: xenial
os: linux

addons:
    apt_packages:
        - lib32z1
        - lib32stdc++6

language: c

env:
  global:
    
    - INCLUDE=addons/sourcemod/scripting/include
    - SCRIPTING=addons/sourcemod/scripting
  jobs:
    - SMVERSION=1.10

install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - chmod +x $SCRIPTING/spcomp
    - mkdir $SCRIPTING/compiled
    - cp -R scripting addons/sourcemod/

script:
    - $SCRIPTING/spcomp -E -o$SCRIPTING'/compiled/ccprocessor' -v0 $SCRIPTING'/ccprocessor.sp'

notifications:
    email: false